Better named specs from user guide

diff --git a/scripts/generate-index-example-specs b/scripts/generate-index-example-specs
--- a/scripts/generate-index-example-specs
+++ b/scripts/generate-index-example-specs
@@ -2,14 +2,46 @@
 
 newline=$'\n'
 
+exampleNames=()
 examples=()
 readingExample=false
 waitingForOutputBlock=false
 readingOutputBlock=false
 
+mostRecentH1=''
+mostRecentH2=''
+mostRecentH5=''
+
+lineNumber=0
+
 while IFS="" read -r line || [ -n "$line" ]
 do
-  if [ "$line" = "<!-- OUTPUT -->" ]
+  (( lineNumber++ ))
+  if [[ "$line" =~ ^\#[[:space:]](.*)$ ]] && [ "$readingExample" = false ] && [ "$readingOutputBlock" = false ]
+  then
+    mostRecentH1="${BASH_REMATCH[1]}"
+    echo "$mostRecentH1"
+    mostRecentH2=''
+    mostRecentH5=''
+  elif [[ "$line" =~ ^\#\#[[:space:]]\[\`([^\]]+)\`\].*$ ]] && [ "$readingExample" = false ] && [ "$readingOutputBlock" = false ]
+  then
+    mostRecentH2="${BASH_REMATCH[1]}"
+    echo "  $mostRecentH2"
+    mostRecentH5=''
+  elif [[ "$line" =~ ^\#\#[[:space:]](.*)$ ]] && [ "$readingExample" = false ] && [ "$readingOutputBlock" = false ]
+  then
+    mostRecentH2="${BASH_REMATCH[1]}"
+    echo "  $mostRecentH2"
+    mostRecentH5=''
+  elif [[ "$line" =~ ^\#\#\#\#\#[[:space:]]\[\`([^\]]+)\`\].*$ ]] && [ "$readingExample" = false ] && [ "$readingOutputBlock" = false ]
+  then
+    mostRecentH5="${BASH_REMATCH[1]}"
+    echo "    $mostRecentH5"
+  elif [[ "$line" =~ ^\#\#\#\#\#[[:space:]](.*)$ ]] && [ "$readingExample" = false ] && [ "$readingOutputBlock" = false ]
+  then
+    mostRecentH5="${BASH_REMATCH[1]}"
+    echo "    $mostRecentH5"
+  elif [ "$line" = "<!-- OUTPUT -->" ]
   then
     # Add a `- code` to the previous example block
     # and now continue reading into it
@@ -22,6 +54,12 @@ do
     waitingForOutputBlock=false
   elif [[ "$line" =~ ^\`\`\`sh ]]
   then
+    exampleName="$mostRecentH1 $mostRecentH2 $mostRecentH5"
+    exampleName="${exampleName//[^a-zA-Z0-9]/_}"
+    exampleName="${exampleName//__/_}"
+    exampleName="${exampleName%_}"
+    exampleNames+=("$exampleName")
+    [ -z "${exampleName// /}" ] && { echo "Missing name for example at line number $lineNumber" >&2; exit 1; }
     examples+=("") 
     readingExample=true
   elif [[ "$line" =~ ^\`\`\` ]]
@@ -51,7 +89,8 @@ specNumber=1
 while [ $exampleIndex -lt "${#examples[@]}" ]
 do
   source="${examples[$exampleIndex]}"
-  specFile="$dir/example$specNumber.spec.sh"
+  exampleName="${exampleNames[$exampleIndex]}"
+  specFile="$dir/${exampleName// /_}.spec.sh"
 
   exampleNumber=1
   commands=()
